from pathlib import Path
import json
import os
import shutil

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"

FILES = ("index.html", "404.html", "robots.txt", "sitemap.xml")
DIRS = ("assets", "icons", "demo")
ANALYTICS_PAGES = (
    "index.html",
    "demo/live-match/index.html",
    "demo/tracking/index.html",
    "demo/player/index.html",
)
ANALYTICS_TAGS = """<script src=\"/assets/analytics-config.js\" defer></script>
<script src=\"/assets/analytics.js\" defer></script>"""


def env_bool(name, default=True):
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def analytics_config():
    key = os.getenv("POSTHOG_KEY", "").strip()
    return {
        "provider": "posthog",
        "enabled": bool(key),
        "projectKey": key,
        "apiHost": os.getenv("POSTHOG_HOST", "https://eu.i.posthog.com").strip(),
        "defaults": "2026-05-30",
        "consentRequired": env_bool("POSTHOG_CONSENT_REQUIRED", True),
        "respectDoNotTrack": env_bool("POSTHOG_RESPECT_DNT", True),
        "environment": os.getenv("CF_PAGES_BRANCH", "local").strip() or "local",
        "release": os.getenv("CF_PAGES_COMMIT_SHA", "local").strip() or "local",
    }


def write_analytics_config():
    config = analytics_config()
    target = DIST / "assets" / "analytics-config.js"
    target.write_text(
        "// Generated by scripts/build_pages.py; do not edit dist directly.\n"
        + "window.__TA_ANALYTICS__ = Object.freeze("
        + json.dumps(config, ensure_ascii=False, separators=(",", ":"))
        + ");\n",
        encoding="utf-8",
    )
    return config


def inject_analytics():
    for relative in ANALYTICS_PAGES:
        path = DIST / relative
        if not path.exists():
            raise SystemExit(f"missing analytics page: {relative}")
        html = path.read_text(encoding="utf-8")
        if "/assets/analytics.js" not in html:
            if "</body>" not in html:
                raise SystemExit(f"missing </body> for analytics injection: {relative}")
            html = html.replace("</body>", f"{ANALYTICS_TAGS}\n</body>", 1)
            path.write_text(html, encoding="utf-8")


def main():
    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir()

    for name in FILES:
        src = ROOT / name
        if not src.exists():
            raise SystemExit(f"missing deploy file: {name}")
        shutil.copy2(src, DIST / name)

    for name in DIRS:
        src = ROOT / name
        if not src.exists():
            raise SystemExit(f"missing deploy directory: {name}")
        shutil.copytree(src, DIST / name)

    config = write_analytics_config()
    inject_analytics()

    print("Cloudflare Pages bundle ready:", DIST)
    print(
        "Analytics:",
        "provider=posthog",
        f"enabled={str(config['enabled']).lower()}",
        f"consent_required={str(config['consentRequired']).lower()}",
        f"respect_dnt={str(config['respectDoNotTrack']).lower()}",
    )
    for path in sorted(DIST.rglob("*")):
        if path.is_file():
            print("-", path.relative_to(DIST))


if __name__ == "__main__":
    main()
